[profile.default]
src = "contracts/src"
test = "contracts/test"
out = "contracts/out"
broadcast = "contracts/broadcast"
libs = ["contracts/lib"]
script = "contracts/script"
cache_path = "contracts/cache"
remappings = [
  "solady=contracts/lib/solady/src/",
  "@openzeppelin/contracts/=contracts/lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/", 
  "@openzeppelin/contracts-upgradeable=contracts/lib/openzeppelin-contracts-upgradeable/contracts/",
  "ens-contracts=contracts/lib/ens-contracts/contracts/", 
  "@ensdomains/buffer=contracts/lib/buffer/"
]
optimizer = true
# Necessary for openzeppelin upgrades plugins
# https://docs.openzeppelin.com/upgrades-plugins/1.x/foundry-upgrades
ast = true
ffi = true
build_info = true
extra_output = ["storageLayout"]

solc = "0.8.24"
evm_version = "cancun"

fs_permissions = [
  { path = "dist/frontend-factory/", access = "read" }, 
  { path = "dist/frontend-welcome/", access = "read" }, 
  { path = "assets/", access = "read" },
  { path = "contracts/out/", access = "read" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
